# Generated by Django 6.0.6 on 2026-06-23 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzmovi', '0003_category_created_at_narsalar_delete_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='narsalar',
            name='name',
        ),
        migrations.AddField(
            model_name='narsalar',
            name='narxi',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='narsalar',
            name='nomi',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
